---
bills:
- name: Amazon Prime
  amount: 16
  date: 12
  tags:
  - monthly
- name: Canva
  amount: 13
  date: 7
  tags:
  - monthly
- name: PFFCU personal loan
  amount: 221
  date: 26
  tags:
  - monthly
- name: At&t
  amount: 105
  date: 1
  tags: []
- name: Netflix
  amount: 7
  date: 9
  tags:
  - non-essential
  - cancelled
- name: Max
  amount: 11
  date: 12
  tags:
  - non-essential
- name: Audible
  amount: 16
  date: 15
  tags:
  - non-essential
  - cancelled
- name: Paramount +
  amount: 6
  date: 19
  tags:
  - non-essential
  - cancelled
- name: Kindle Unlimited
  amount: 13
  date: 21
  tags:
  - non-essential
  - cancelled
- name: Max Fun
  amount: 5
  date: 30
  tags:
  - non-essential
  - cancelled
- name: Squarespace
  amount: 36
  date: 13
  tags:
  - monthly
  - R.P Dunwater
- name: Rent
  amount: 500
  date: 1
  tags:
  - every check
- name: Spotify
  amount: 16
  date: 21
  tags:
  - music
- name: Car Payment
  amount: 283
  date: 10
  tags: []
- name: Chase
  amount: 0
  date: 7
  tags:
  - credit card
  - cancelled
- name: PFFCU
  amount: 0
  date: 25
  tags:
  - credit card
- name: Discover
  amount: 0
  date: 28
  tags:
  - credit card
  - cancelled
- name: Capital One
  amount: 
  date: 28
  tags:
  - credit card
  - cancelled
- name: Food budget
  amount: 400
  date: '0'
  tags:
  - every check
- name: Car Insurance Holding
  amount: 50
  date: '0'
  tags:
  - every check
- name: Car Maintenance
  amount: 85
  date: '0'
  tags:
  - every check
- name: Dog Fund
  amount: 70
  date: '0'
  tags:
  - every check
- name: Keeps Holding
  amount: 20
  date: '0'
  tags:
  - every check
- name: Hers Holding
  amount: 30
  date: '0'
  tags:
  - every check
- name: House Fund
  amount: 50
  date: '0'
  tags:
  - every check
- name: PFFCU personal loan
  amount: 221
  date: 26
  tags:
  - monthly
- name: Chat.OpenAI
  amount: 20
  date: 3
  tags:
  - monthly
  - non-essential
  - cancelled
# - name: Care Credit
#   amount: 100
#   date: 0
#   tags:
#   - credit card
#   - every check 
#   - cancelled
- name: Newegg card
  amount: 100
  date: 0
  tags:
  - every check
- name: BarkBox
  amount: 30
  date: 1
  tags:
  - non-essential
  - cancelled
- name: MTG Delver lens
  amount: 4
  date: 7
  tags:
  - non-essential
  - cancelled
- name: MailerLite
  amount: 25
  date: 24
  tags: 
  - monthly
  - R.P Dunwater
- name: Wikipedia
  amount: 2
  date: 7
  tags: 
  - non-essential
- name: Nintendo Online
  amount: 5
  date: 26
  tags: 
  - non-essential
