monthly_bills: 
  - name: Rent 
    amount: 850
    date_number: 1
  - name: at&t
    amount: 70
    date_number: 1
  - name: Comcast
    amount: 95
    date_number: 7
  - name: car payment
    amount: 283
    date_number: 10 
  - name: Amazon Prime
    amount: 14
    date_number: 12
  - name: Electric
    amount: 70
    date_number: 14
  - name: Renter's insurance
    amount: 15
    date_number: 20 
  - name: Spotify
    amount: 14
    date_number: 21


credit_cards:
  - name: Chase 
    amount: 50 
    date_number: 7
  - name: PFFCU
    amount: 25
    date_number: 25
  - name: Capital One 
    amount: 65
    date_number: 28
  - name: Discover 
    amount: 150 
    date_number: 28 

every_check: 
  - name: Care Credit
    amount: 100
  - name: dog fund
    amount: 50
  - name: Food budget
    amount: 300
  - name: car insurance holding 
    amount: 50 
  - name: car maintenance fund 
    amount: 50 




  


