---
bills:
- name: Amazon Prime
  amount: 16
  date: 12
  tags:
  - monthly
  source: ''
- name: Canva
  amount: 13
  date: 7
  tags:
  - monthly
  source: ''
- name: PFFCU personal loan
  amount: 221
  date: 26
  tags:
  - monthly
  source: ''
- name: At&t
  amount: 125
  date: 1
  tags: []
  source: ''
- name: Netflix
  amount: 7
  date: 9
  tags:
  - non-essential
  - cancelled
  source: ''
- name: Max
  amount: 11
  date: 12
  tags:
  - non-essential
  source: ''
- name: Audible
  amount: 16
  date: 15
  tags:
  - non-essential
  - cancelled
  source: ''
- name: Paramount +
  amount: 6
  date: 19
  tags:
  - non-essential
  - cancelled
  source: ''
- name: Kindle Unlimited
  amount: 13
  date: 21
  tags:
  - non-essential
  - cancelled
  source: ''
- name: Max Fun
  amount: 5
  date: 30
  tags:
  - non-essential
  source: ''
- name: Squarespace
  amount: 36
  date: 13
  tags:
  - monthly
  - R.P Dunwater
  source: ''
- name: Rent
  amount: 600
  date: 1
  tags:
  - every check
  source: ''
- name: Spotify
  amount: 16
  date: 21
  tags:
  - music
  source: ''
- name: Car Payment
  amount: 283
  date: 10
  tags: []
  source: ''
- name: Chase
  amount: 100
  date: 0
  tags:
  - credit card
  - every check
  source: ''
- name: PFFCU
  amount: 50
  date: 25
  tags:
  - credit card
  source: ''
- name: Discover
  amount: 0
  date: 28
  tags:
  - credit card
  - cancelled
  source: ''
- name: Capital One
  amount:
  date: 28
  tags:
  - credit card
  - cancelled
  source: ''
- name: Food budget
  amount: 500
  date: '0'
  tags:
  - every check
  source: ''
- name: car insurance holding
  amount: 115
  date: '0'
  tags:
  - every check
  source: ''
- name: Car Maintenance
  amount: 85
  date: '0'
  tags:
  - every check
  source: ''
- name: Dog Fund
  amount: 75
  date: '0'
  tags:
  - every check
  source: ''
- name: Keeps Holding
  amount: 20
  date: '0'
  tags:
  - every check
  - every check
  source: ''
- name: PFFCU personal loan
  amount: 221
  date: 26
  tags:
  - monthly
  source: ''
- name: Chat.OpenAI
  amount: 0
  date: 3
  tags:
  - cancelled
  - monthly
  - non-essential
  source: ''
- name: Care Credit
  amount: 100
  date: 0
  tags:
  - every check
  source: ''
- name: Newegg card
  amount: 100
  date: 1
  tags:
  - cancelled
  source: ''
- name: BarkBox
  amount: 30
  date: 1
  tags:
  - non-essential
  - cancelled
  source: ''
- name: MTG Delver lens
  amount: 4
  date: 7
  tags:
  - non-essential
  - cancelled
  source: ''
- name: MailerLite
  amount: 25
  date: 24
  tags:
  - monthly
  - R.P Dunwater
  source: ''
- name: Wikipedia
  amount: 2
  date: 7
  tags:
  - non-essential
  source: ''
- name: Nintendo Online
  amount: 5
  date: 26
  tags:
  - non-essential
  source: ''
